[settings]
current=catppuccin

[ayu]
primary_color=#B8CC52
wallpaper=~/.dotfiles/wallpapers/ayu/ayu1.jpg
nvim=ayu
ghostty=ayu-fix
waybar=ayu

[catppuccin]
primary_color=#A6E3A1
wallpaper=~/.dotfiles/wallpapers/catppuccin/catppuccin-wall-e.jpg
nvim=catppuccin-mocha
ghostty=catppuccin-mocha
waybar=catppuccin-mocha
