[settings]
current=catppuccin-mocha

[ayu]
primary_color=#B8CC52
wallpaper=~/.dotfiles/wallpapers/ayu/ayu1.jpg
nvim=ayu
ghostty=ayu-fix
waybar=ayu
tmux=ayu

[catppuccin-mocha]
primary_color=#A6E3A1
wallpaper=~/wallpapers/catppuccin/2024-10-22-09-35-48-abstract-swirls.jpg
nvim=catppuccin-mocha
ghostty=catppuccin-mocha
waybar=catppuccin-mocha
tmux=catppuccin
