[settings]
current=catppuccin-mocha

[ayu]
primary_color=#B8CC52
rounding=10
animations=on
gaps=8
wallpaper=~/.dotfiles/wallpapers/ayu/ayu2.jpg
nvim=ayu
ghostty=ayu-fix
waybar=ayu
tmux=ayu
gtk=juno-mirage
swaync=ayu
spotify=Sleek,AyuDark

[catppuccin-mocha]
primary_color=#A6E3A1
rounding=10
animations=on
gaps=8
wallpaper=~/wallpapers/catppuccin/laundry.jpg
nvim=catppuccin-mocha
ghostty=catppuccin-mocha
waybar=catppuccin-mocha
gtk=catppuccin-mocha
swaync=catppuccin-mocha
tmux=catppuccin
spotify=Sleek,Catppuccin

[mono]
primary_color=#f28779
rounding=0
animations=off
gaps=1
wallpaper=~/wallpapers/mono/mono1.png
nvim=onedark
ghostty=mono
waybar=mono
gtk=ayu
swaync=mono
tmux=mono
spotify=Sleek,AyuDark
