# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Decorations Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/colors.conf

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#decoration

# disable gtk titlebar buttons (close, minimize, maximize)
exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout ''

decoration {
    rounding =  0

    inactive_opacity = 0.90
    active_opacity = 0.90

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#blur
    # blur {
    #     size = 15
    #     passes = 2 # more passes = more resource intensive.
    #     xray = true
    # }
    blur {
        enabled = on
        size = 5
        passes = 2
        xray = true
        special = on
        new_optimizations = on
        vibrancy = 0.1696
    }

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#shadow
    shadow {
        enabled = false
    }

}
