# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$screenshot = grim -g "$(slurp)" - | wl-copy -t image/png
$terminal = ghostty
$filemanager = thunar
$applauncher = rofi -show drun
$browser = zen-browser
$keyboardToggle = $HOME/.config/hypr/scripts/keyboard_util.sh --toggle
$themeswitcher = $HOME/.config/themer/rofi-themer.sh
$powermenu = $HOME/.config/rofi/powermenu.sh
$monitorswitcher = $HOME/.config/hypr/scripts/switchmonitors.sh
$screenshotRegion = hyprshot -m region -o $HOME/Pictures/Screenshots
$browserCurrentWorkspace = $HOME/.config/hypr/scripts/browserCurrentWorkspace.sh
$betterclose = $HOME/.config/hypr/scripts/betterclose.sh
