# Extra autostart processes
# SET BACKGROUNDS
exec-once = hyprctl setcursor yaru 24
exec-once = uwsm-app -- swaybg -o DP-3 -i ~/Pictures/wallpapers/private/DSCF7116.jpg -m fill
exec-once = uwsm-app -- swaybg -o HDMI-A-1 -i ~/Pictures/wallpapers/private/IMG20240825121628.jpg -m fill
exec-once = [silent] /usr/bin/spotify &
exec-once = [silent] /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.discordapp.Discord --file-forwarding com.discordapp.Discord @@u %U @@ &



# Gaming workspace listeners
## Wallpaper
exec-once = uwsm-app -- ~/.config/hypr/scripts/gamemode-wallpaper.sh
## Auto leave to Workspace 2
exec-once = uwsm-app -- ~/.config/hypr/scripts/leave_game_workspace_on_empty.sh
