# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
    blur {
      enabled = true
      size = 3
      new_optimizations = yes
      ignore_opacity=true
      special = true
    }

    dim_special = 0.2
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
    # preserve_split = true
    force_split = 2
    # smart_split = true
    precise_mouse_move = true
}

binds {
    allow_workspace_cycles = 1
    workspace_back_and_forth = 1
    workspace_center_on = 1
    movefocus_cycles_fullscreen = true
    window_direction_monitor_fallback = true
}
